# Generated by Django 2.2.9 on 2020-01-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200123_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
